/**
 * This file is auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * To regenerate:
 * 1. Start the API server: bun run dev:api
 * 2. Generate schema: bun run openapi
 */

export interface paths {
  "/research": {
    post: {
      parameters: {
        body: {
          query: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              query: string;
              sources: number;
              response: string;
            };
          };
        };
      };
    };
  };
  "/deep-research": {
    post: {
      parameters: {
        body: {
          query: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              query: string;
              sources: number;
              response: string;
            };
          };
        };
      };
    };
  };
  "/multi-agent-research": {
    post: {
      parameters: {
        body: {
          query: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              query: string;
              subagents: number;
              total_sources: number;
              synthesis: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
